spring:
  application:
    name: node-agent

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
